### ISSUE TITLE
[BUG] Php warning: Only the first byte will be assigned to the string offset

### ISSUE THREAD

**Issue by BFallert** [kitodo/kitodo-presentation#1333] opened 2024-09-12 12:58 UTC
## Description

When I open a PageView I get an entry in the Typo3 system / log:
`Core: Error handler (FE): PHP Warning: Only the first byte will be assigned to the string offset in /var/www/html/packages/ub-mannheim/presentation/Classes/Controller/MetadataController.php line 430
`
## Reproduction

Steps to reproduce the behaviour:

1. Select a Document in ListView
2. open that Document
3. Open Typo3-BE
4. open System / Log
5. see the warning message

## Expected Behavior

no warning message

## Screenshots and Examples

![image](https://github.com/user-attachments/assets/116513f0-fd69-4300-aaba-a5e5e829aa26)

## Environment

 - OS version: Linux ddev-digi-new-web 5.15.153.1-microsoft-standard-WSL2
RDBMS version: MySQL 10.11.8-MariaDB-ubu2204-log
Apache Solr version: 9.6.1
TYPO3 version: 11.5.40
PHP version: 8.0.30

## Additional Context

I think the error comes from the line:
````
    private function parseOwner(int $i, array &$metadata) : void
    {
        $library = $this->document->getOwner();
        if ($library) {
            $metadata[$i]['owner'][0] = $library->getLabel();
        }
    }
````
The message is no longer displayed when I remove '[0]', so that not only the first letter but the whole label is inserted.

**Comment by beatrycze-volk** [comment] 2024-09-13 08:26
Related to https://github.com/kitodo/kitodo-presentation/issues/1308 - the metadata values are converted to string, but they shouldn't be.

**Comment by sebastian-meyer** [comment] 2024-10-01 11:27
Closing this, because it is a duplicate of #1308.

**Closed as completed by sebastian-meyer** 2024-10-01 11:27 UTC
Labels: ☇ bug, ⎘ duplicate
