### ISSUE TITLE
search truncation with * does not work any longer

### ISSUE THREAD

**Issue by KatharinaLemke** [kitodo/kitodo-presentation#150] opened 2016-09-27 08:29 UTC
As mentioned in issue#21 search truncation with \* does not work any longer (since fix#34).
Using '\*' still works - but 'fragment\*' does not work.
This kind of search is very important for our users.

**Comment by stweil** [comment] 2016-09-27 12:32
Links: issue #21, pull request #34.

**Comment by sebastian-meyer** [comment] 2017-12-18 15:37
Duplicate of #21 
Should be fixed with #34

**Comment by stweil** [comment] 2017-12-18 16:30
Are you sure this is fixed? @KatharinaLemke reported it long after fix #34. As I understand this issue, it was _introduced_ by #34. See also [this comment](https://github.com/kitodo/kitodo-presentation/issues/21#issuecomment-85510295). It looks like Katharina's issue description is incomplete because some important characters were interpreted as markdown formatting.

**Comment by sebastian-meyer** [comment] 2017-12-20 09:44
Thanks for clarifying! You were right: I misinterpreted the bug report because of the markdown formatting. I fixed the bug report and reopened the issue.

**Comment by sebastian-meyer** [comment] 2019-10-08 14:44
I've looked into this. The issue is using Solarium's `escapeTerm()` function which escapes all characters that has a special meaning - including `*` ([see for yourself](https://github.com/solariumphp/solarium/blob/80b87ea3812b2726302ba07fa153b208318a5dac/src/Core/Query/Helper.php#L68)).

We can't fix this without implementing our own escape function which retains some special characters like `*` and `?`. This would be easy but causes additional maintenance load since we would have to keep our escape method up-to-date with potential future Solr changes.

**Closed as completed** 2019-11-14 08:46 UTC
Labels: ☇ bug
