### ISSUE TITLE
[BUG] Issues after merging #885

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-presentation#1029] opened 2023-09-28 10:46 UTC
**Tests under TYPO3 v10 with [our DFG-Viewer](https://github.com/UB-Mannheim/dfg-viewer/tree/6.x-ocr):**

- Everything search related is still not working. See my comment from [24 feb](https://github.com/kitodo/kitodo-presentation/pull/885#issuecomment-1443367080). Is it just me?
- The thumbnail preview (gridpage) shows only the first 24 pages and has no option to load more pages: (dfg-viewer issue?)
![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/4cbd4f32-513a-4826-80c6-d22bca50ddcc)
Short addition: On an other document the text part was partially linked. First 24 pages with working link for the next 24:
![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/67777cbf-0915-4105-9958-b6dae89c8d9d)
but the next page had only a working link back:
![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/bfc0bbe8-9d45-4978-b913-5e80074f1e4b)
The two mentioned mets: https://digi.bib.uni-mannheim.de/fileadmin/vl/ubmaosi/59087/59087.xml and https://digi.bib.uni-mannheim.de/fileadmin/vl/ubmaosi/59088/59088.xml
- In addition, the numbers 1 and 31 refer to the number of review pages. But are somehow incorrectly displayed / placed. For reference, how it currently looks (and should be looking):
![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/51a2087d-0936-4f37-8d68-2ec2a05ffbe8)

- The image manipulation tools are missing: (dfg-viewer issue?)
![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/0aee3153-981b-4edf-b6b5-07a24dac4619)

- the same Metadata pairing/grouping issue described later

**Tests under TYPO3 v11:**
- I could not get the viewer running. But that can be on me. I had always issues manually setting presentation up. Ill try more. Is there anywhere a step by step guide?
  -> I could not try the viewer or anything related 
- New Tenant Module:
  - Can not create a new Solr Core:
![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/7876cff6-45ad-4b9d-b649-4436936f2f4d)
    -> I did not set the correct solr configuration prior. But till v10 this wasn't necessary.
  -  After creating namespaces, Structures and Metadata they aren't "grouped" or "paired" by language any more:
   ![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/954c3eb1-c6ef-47bc-b08f-6904357a0bb9) ![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/453dd125-63d5-4b1a-baa5-61904395e875)
- Analyze Database Structure shows:
```
Add tables
    CREATE TABLE tx_dlf_documents (`uid` INT AUTO_INCREMENT NOT NULL, `pid` INT DEFAULT 0 NOT NULL, `tstamp` INT DEFAULT 0 NOT NULL, `crdate` INT DEFAULT 0 NOT NULL, `cruser_id` INT DEFAULT 0 NOT NULL, `deleted` SMALLINT DEFAULT 0 NOT NULL, `hidden` SMALLINT DEFAULT 0 NOT NULL, `starttime` INT DEFAULT 0 NOT NULL, `endtime` INT DEFAULT 0 NOT NULL, `fe_group` VARCHAR(100) DEFAULT '' NOT NULL, `prod_id` VARCHAR(255) DEFAULT '' NOT NULL, `location` VARCHAR(255) DEFAULT '' NOT NULL, `record_id` VARCHAR(255) DEFAULT '' NOT NULL, `opac_id` VARCHAR(255) DEFAULT '' NOT NULL, `union_id` VARCHAR(255) DEFAULT '' NOT NULL, `urn` VARCHAR(255) DEFAULT '' NOT NULL, `purl` VARCHAR(255) DEFAULT '' NOT NULL, `title` TEXT NOT NULL, `title_sorting` TEXT NOT NULL, `author` VARCHAR(255) DEFAULT '' NOT NULL, `year` VARCHAR(255) DEFAULT '' NOT NULL, `place` VARCHAR(255) DEFAULT '' NOT NULL, `thumbnail` VARCHAR(255) DEFAULT '' NOT NULL, `structure` INT DEFAULT 0 NOT NULL, `partof` INT DEFAULT 0 NOT NULL, `volume` VARCHAR(255) DEFAULT '' NOT NULL, `volume_sorting` VARCHAR(255) DEFAULT '' NOT NULL, `license` VARCHAR(255) DEFAULT '' NOT NULL, `terms` VARCHAR(255) DEFAULT '' NOT NULL, `restrictions` VARCHAR(255) DEFAULT '' NOT NULL, `out_of_print` TEXT NOT NULL, `rights_info` TEXT NOT NULL, `collections` INT DEFAULT 0 NOT NULL, `mets_label` TEXT NOT NULL, `mets_orderlabel` TEXT NOT NULL, `owner` INT DEFAULT 0 NOT NULL, `solrcore` INT DEFAULT 0 NOT NULL, `status` SMALLINT UNSIGNED DEFAULT 0 NOT NULL, `document_format` VARCHAR(100) DEFAULT '' NOT NULL, INDEX `parent` (pid), INDEX `location` (location), INDEX `record_id` (record_id), INDEX `partof` (partof), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
    CREATE TABLE tx_dlf_structures (`uid` INT AUTO_INCREMENT NOT NULL, `pid` INT DEFAULT 0 NOT NULL, `tstamp` INT DEFAULT 0 NOT NULL, `crdate` INT DEFAULT 0 NOT NULL, `cruser_id` INT DEFAULT 0 NOT NULL, `deleted` SMALLINT DEFAULT 0 NOT NULL, `sys_language_uid` INT DEFAULT 0 NOT NULL, `l18n_diffsource` MEDIUMBLOB NOT NULL, `hidden` SMALLINT DEFAULT 0 NOT NULL, `l18n_parent` INT DEFAULT 0 NOT NULL, `toplevel` SMALLINT DEFAULT 0 NOT NULL, `label` VARCHAR(255) DEFAULT '' NOT NULL, `index_name` VARCHAR(255) DEFAULT '' NOT NULL, `oai_name` VARCHAR(255) DEFAULT '' NOT NULL, `thumbnail` INT DEFAULT 0 NOT NULL, `status` SMALLINT UNSIGNED DEFAULT 0 NOT NULL, INDEX `parent` (pid), INDEX `language` (l18n_parent, sys_language_uid), INDEX `index_name` (index_name), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
    CREATE TABLE tx_dlf_metadata (`uid` INT AUTO_INCREMENT NOT NULL, `pid` INT DEFAULT 0 NOT NULL, `tstamp` INT DEFAULT 0 NOT NULL, `crdate` INT DEFAULT 0 NOT NULL, `cruser_id` INT DEFAULT 0 NOT NULL, `deleted` SMALLINT DEFAULT 0 NOT NULL, `sys_language_uid` INT DEFAULT 0 NOT NULL, `l18n_diffsource` MEDIUMBLOB NOT NULL, `hidden` SMALLINT DEFAULT 0 NOT NULL, `sorting` INT DEFAULT 0 NOT NULL, `l18n_parent` INT DEFAULT 0 NOT NULL, `label` VARCHAR(255) DEFAULT '' NOT NULL, `index_name` VARCHAR(255) DEFAULT '' NOT NULL, `format` INT DEFAULT 0 NOT NULL, `default_value` VARCHAR(255) DEFAULT '' NOT NULL, `wrap` TEXT NOT NULL, `index_tokenized` SMALLINT DEFAULT 0 NOT NULL, `index_stored` SMALLINT DEFAULT 0 NOT NULL, `index_indexed` SMALLINT DEFAULT 0 NOT NULL, `index_boost` DOUBLE PRECISION DEFAULT '1.00' NOT NULL, `is_sortable` SMALLINT DEFAULT 0 NOT NULL, `is_facet` SMALLINT DEFAULT 0 NOT NULL, `is_listed` SMALLINT DEFAULT 0 NOT NULL, `index_autocomplete` SMALLINT DEFAULT 0 NOT NULL, `status` SMALLINT UNSIGNED DEFAULT 0 NOT NULL, INDEX `parent` (pid), INDEX `language` (l18n_parent, sys_language_uid), INDEX `index_name` (index_name), INDEX `index_autocomplete` (index_autocomplete), INDEX `is_sortable` (is_sortable), INDEX `is_facet` (is_facet), INDEX `is_listed` (is_listed), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
    CREATE TABLE tx_dlf_metadataformat (`uid` INT AUTO_INCREMENT NOT NULL, `pid` INT DEFAULT 0 NOT NULL, `tstamp` INT DEFAULT 0 NOT NULL, `crdate` INT DEFAULT 0 NOT NULL, `cruser_id` INT DEFAULT 0 NOT NULL, `deleted` SMALLINT DEFAULT 0 NOT NULL, `sys_language_uid` INT DEFAULT 0 NOT NULL, `l18n_parent` INT DEFAULT 0 NOT NULL, `parent_id` INT DEFAULT 0 NOT NULL, `encoded` INT DEFAULT 0 NOT NULL, `xpath` VARCHAR(1024) DEFAULT '' NOT NULL, `xpath_sorting` VARCHAR(1024) DEFAULT '' NOT NULL, `mandatory` SMALLINT DEFAULT 0 NOT NULL, INDEX `parent` (pid), INDEX `parent_id` (parent_id), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
    CREATE TABLE tx_dlf_formats (`uid` INT AUTO_INCREMENT NOT NULL, `pid` INT DEFAULT 0 NOT NULL, `tstamp` INT DEFAULT 0 NOT NULL, `crdate` INT DEFAULT 0 NOT NULL, `cruser_id` INT DEFAULT 0 NOT NULL, `deleted` SMALLINT DEFAULT 0 NOT NULL, `type` VARCHAR(255) DEFAULT '' NOT NULL, `root` VARCHAR(255) DEFAULT '' NOT NULL, `namespace` VARCHAR(255) DEFAULT '' NOT NULL, `class` VARCHAR(255) DEFAULT '' NOT NULL, INDEX `parent` (pid), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
    CREATE TABLE tx_dlf_solrcores (`uid` INT AUTO_INCREMENT NOT NULL, `pid` INT DEFAULT 0 NOT NULL, `tstamp` INT DEFAULT 0 NOT NULL, `crdate` INT DEFAULT 0 NOT NULL, `cruser_id` INT DEFAULT 0 NOT NULL, `deleted` SMALLINT DEFAULT 0 NOT NULL, `label` VARCHAR(255) DEFAULT '' NOT NULL, `index_name` VARCHAR(255) DEFAULT '' NOT NULL, INDEX `parent` (pid), INDEX `index_name` (index_name), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
    CREATE TABLE tx_dlf_collections (`uid` INT AUTO_INCREMENT NOT NULL, `pid` INT DEFAULT 0 NOT NULL, `tstamp` INT DEFAULT 0 NOT NULL, `crdate` INT DEFAULT 0 NOT NULL, `cruser_id` INT DEFAULT 0 NOT NULL, `deleted` SMALLINT DEFAULT 0 NOT NULL, `sys_language_uid` INT DEFAULT 0 NOT NULL, `l18n_diffsource` MEDIUMBLOB NOT NULL, `hidden` SMALLINT DEFAULT 0 NOT NULL, `fe_group` VARCHAR(100) DEFAULT '' NOT NULL, `fe_cruser_id` INT DEFAULT 0 NOT NULL, `fe_admin_lock` SMALLINT DEFAULT 0 NOT NULL, `l18n_parent` INT DEFAULT 0 NOT NULL, `label` VARCHAR(255) DEFAULT '' NOT NULL, `index_name` VARCHAR(255) DEFAULT '' NOT NULL, `index_search` TEXT NOT NULL, `oai_name` VARCHAR(255) DEFAULT '' NOT NULL, `description` TEXT NOT NULL, `thumbnail` VARCHAR(255) DEFAULT '' NOT NULL, `priority` SMALLINT DEFAULT 3 NOT NULL, `documents` INT DEFAULT 0 NOT NULL, `owner` INT DEFAULT 0 NOT NULL, `status` SMALLINT UNSIGNED DEFAULT 0 NOT NULL, INDEX `parent` (pid), INDEX `language` (l18n_parent, sys_language_uid), INDEX `index_name` (index_name), INDEX `oai_name` (oai_name), INDEX `pid_cruser` (pid, fe_cruser_id), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
    CREATE TABLE tx_dlf_libraries (`uid` INT AUTO_INCREMENT NOT NULL, `pid` INT DEFAULT 0 NOT NULL, `tstamp` INT DEFAULT 0 NOT NULL, `crdate` INT DEFAULT 0 NOT NULL, `cruser_id` INT DEFAULT 0 NOT NULL, `deleted` SMALLINT DEFAULT 0 NOT NULL, `sys_language_uid` INT DEFAULT 0 NOT NULL, `l18n_diffsource` MEDIUMBLOB NOT NULL, `l18n_parent` INT DEFAULT 0 NOT NULL, `label` VARCHAR(255) DEFAULT '' NOT NULL, `index_name` VARCHAR(255) DEFAULT '' NOT NULL, `website` VARCHAR(255) DEFAULT '' NOT NULL, `contact` VARCHAR(255) DEFAULT '' NOT NULL, `image` VARCHAR(255) DEFAULT '' NOT NULL, `oai_label` VARCHAR(255) DEFAULT '' NOT NULL, `oai_base` VARCHAR(255) DEFAULT '' NOT NULL, `opac_label` VARCHAR(255) DEFAULT '' NOT NULL, `opac_base` VARCHAR(255) DEFAULT '' NOT NULL, `union_label` VARCHAR(255) DEFAULT '' NOT NULL, `union_base` VARCHAR(255) DEFAULT '' NOT NULL, INDEX `parent` (pid), INDEX `language` (l18n_parent, sys_language_uid), INDEX `index_name` (index_name), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
    CREATE TABLE tx_dlf_tokens (`uid` INT AUTO_INCREMENT NOT NULL, `pid` INT DEFAULT 0 NOT NULL, `tstamp` INT DEFAULT 0 NOT NULL COMMENT 'Timestamp of the token used to determine if it has expired.', `crdate` INT UNSIGNED DEFAULT 0 NOT NULL, `cruser_id` INT UNSIGNED DEFAULT 0 NOT NULL, `token` VARCHAR(255) DEFAULT '' NOT NULL, `options` MEDIUMTEXT NOT NULL, `ident` VARCHAR(30) DEFAULT '' NOT NULL, INDEX `parent` (pid), INDEX `token` (token), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
    CREATE TABLE `tx_dlf_relations` (`uid` INT AUTO_INCREMENT NOT NULL, `uid_local` INT DEFAULT 0 NOT NULL, `uid_foreign` INT DEFAULT 0 NOT NULL, `tablenames` VARCHAR(30) DEFAULT '' NOT NULL, `sorting` INT DEFAULT 0 NOT NULL, `sorting_foreign` INT DEFAULT 0 NOT NULL, `ident` VARCHAR(30) DEFAULT '' NOT NULL COMMENT 'An identifier to describe which tables are matched.', INDEX `local_foreign` (uid_local, uid_foreign, ident), INDEX `uid_local` (uid_local), INDEX `uid_foreign` (uid_foreign), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = 'Pivot table for many-to-many relations between tables. In particular, this is used to match documents and collections by using ident=docs_colls.'
    CREATE TABLE tx_dlf_basket (`uid` INT AUTO_INCREMENT NOT NULL, `pid` INT DEFAULT 0 NOT NULL, `tstamp` INT DEFAULT 0 NOT NULL, `deleted` SMALLINT DEFAULT 0 NOT NULL, `sys_language_uid` INT DEFAULT 0 NOT NULL, `l18n_diffsource` MEDIUMBLOB NOT NULL, `fe_user_id` INT DEFAULT 0 NOT NULL, `l18n_parent` INT DEFAULT 0 NOT NULL, `label` VARCHAR(255) DEFAULT '' NOT NULL, `session_id` VARCHAR(32) DEFAULT '' NOT NULL, `doc_ids` VARCHAR(255) DEFAULT '' NOT NULL, INDEX `parent` (pid), INDEX `language` (l18n_parent, sys_language_uid), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
    CREATE TABLE tx_dlf_printer (`uid` INT AUTO_INCREMENT NOT NULL, `pid` INT DEFAULT 0 NOT NULL, `deleted` SMALLINT DEFAULT 0 NOT NULL, `print` VARCHAR(255) DEFAULT '' NOT NULL, `label` VARCHAR(255) DEFAULT '' NOT NULL, INDEX `parent` (pid), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
    CREATE TABLE tx_dlf_mail (`uid` INT AUTO_INCREMENT NOT NULL, `pid` INT DEFAULT 0 NOT NULL, `deleted` SMALLINT DEFAULT 0 NOT NULL, `sorting` INT DEFAULT 0 NOT NULL, `mail` VARCHAR(255) DEFAULT '' NOT NULL, `name` VARCHAR(255) DEFAULT '' NOT NULL, `label` VARCHAR(255) DEFAULT '' NOT NULL, INDEX `parent` (pid), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
    CREATE TABLE tx_dlf_actionlog (`uid` INT AUTO_INCREMENT NOT NULL, `pid` INT DEFAULT 0 NOT NULL, `crdate` INT DEFAULT 0 NOT NULL, `deleted` SMALLINT DEFAULT 0 NOT NULL, `user_id` INT DEFAULT 0 NOT NULL, `file_name` VARCHAR(255) DEFAULT '' NOT NULL, `count_pages` INT DEFAULT 0 NOT NULL, `name` VARCHAR(100) DEFAULT '' NOT NULL, `label` VARCHAR(255) DEFAULT '' NOT NULL, INDEX `parent` (pid), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
```

_Originally posted by @csidirop in https://github.com/kitodo/kitodo-presentation/issues/885#issuecomment-1737628226_

**Comment by beatrycze-volk** [comment] 2023-09-28 10:57
> * The image manipulation tools are missing: (dfg-viewer issue?)

https://github.com/slub/dfg-viewer/pull/235 needs to be merged to DFG-Viewer before toolbox will work again.

**Comment by csidirop** [comment] 2023-09-28 12:30
> [slub/dfg-viewer#235](https://github.com/slub/dfg-viewer/pull/235) needs to be merged to DFG-Viewer before toolbox will work again.

Oh right, that was the same issue like the fulltext button.

**Comment by csidirop** [comment] 2023-10-10 14:06
Can anyone else reproduce this?

**Comment by csidirop** [comment] 2023-10-24 09:50
Did a quick test with the current state. All issues (except the toolbox) are still present for me. 

Is this just me? Are some of them dfg-viewer related? Can you please verify this behaviour?!

> System: 
> - TYPO3 v10.4.28-dev
> - presentation master as of 23.10.23 (ef3d4585eed041baed9ef1912537559d44f1e295), 
> - dfg-viewer master as of 19.10.23 (https://github.com/slub/dfg-viewer/commit/2af0d45027c5892059fcbec3acacd2d9b0956d5a), 
> - slub_digitalcollections as of 17.04.23 (https://github.com/slub/slub_digitalcollections/commit/049e1a777701c2ae8c8e4093ee0ea89c884e512b) with following PRs merged: https://github.com/slub/slub_digitalcollections/pull/51 https://github.com/slub/slub_digitalcollections/pull/55 .
> 

Not tested for TYPO3 v11.

**Comment by csidirop** [comment] 2023-11-02 09:36
>     * Everything search related is still not working. See my comment from [24 feb](https://github.com/kitodo/kitodo-presentation/pull/885#issuecomment-1443367080). Is it just me?

@BFallert may found a reason for this behaviour. There is a wrong call in https://github.com/slub/slub_digitalcollections/blob/master/Resources/Private/Plugins/SingleCollection/Templates/Show.html#L24 . I believe this was not updated after the pagination update in .presentation. 

Changing `widgetPage` to `pagination` fixes the error partially:
![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/e1258619-4ca3-43c9-bf06-b37e7babecb7)

But there is an other issue which we will be documenting asap.

**Comment by csidirop** [comment] 2023-11-02 15:34
>     * The thumbnail preview (gridpage) shows only the first 24 pages and has no option to load more pages: (dfg-viewer issue?)


@BFallert fixed this in [bfallert/pagination](https://github.com/BFallert/kitodo-presentation/tree/fix/pagination) and [bfallert/pagination_missing_between_first_and_last](https://github.com/BFallert/kitodo-presentation/tree/fix/pagination_missing_between_first_and_last) and proposed a PR #1075:

![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/e79d661a-7ddd-4118-9a98-420eae7addf2)

Unfortunatly I cant test this, because we could not solve the first [issue](https://github.com/kitodo/kitodo-presentation/issues/1029#issuecomment-1790380542) for the dfg-viewers page template.

**Comment by csidirop** [comment] 2023-11-03 15:27
After a bit more digging I found following. As you know there are two ways to set up your search pages:
1. Adding a `Kitodo: Search`-element and referencing the page with the `Kitodo: Pageview`-element (or DFG-Viewer) or
2. Adding a `Kitodo: Search`-element and referencing the page with the `Kitodo: List View`-element which then needs a reference to the `Kitodo: Pageview`-element

I'm using the first "short" way. Which produces the `-24 bis 0`-error. The second way not!

Looking bit deeper into it we found that there is the `pagination` variable missing. As you can see in following debug dumps:
*Second way:* 
![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/eb9db52e-9697-44c1-afa2-3483ad7ef8a6)

*First way:*
![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/b680ddfa-817b-47ec-bf78-925ffc280b63)

In fact not only `pagination` is missing, also `paginator ` , `extendedSlotCount ` and `extendedFields` (there are more differences).

**Comment by csidirop** [comment] 2024-01-11 08:35
I believe that all the errors I reported have now been resolved. I will test again next week for TYPO3 v11, but then create separate issues.

@sebastian-meyer can be closed i think

**Closed as completed** 2024-01-30 08:31 UTC
Labels: ☇ bug
